"""Initial migration

Revision ID: a31e48a306dc
Revises: 
Create Date: 2024-05-19 16:14:38.642654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31e48a306dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=64), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=256), nullable=False))
        batch_op.drop_column('file_path')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('model')

    # ### end Alembic commands ###
